version: '3'

services:
    monolith.nginx:
        build:
            context: ./env/monolith/nginx
            dockerfile: Dockerfile
        volumes:
            - ./services/monolith:/var/www/symfony/
        ports:
            - ${MONOLITH_HTTP_PORT:-10001}:80

    monolith.db:
        image: mysql:8.0.20
        command: --default-authentication-plugin=mysql_native_password
        volumes:
            - "monolith_db_volume:/var/lib/mysql"
        environment:
            MYSQL_ROOT_PASSWORD: ${MONOLITH_MYSQL_ROOT_PASSWORD:-hello}
            MYSQL_DATABASE: ${MONOLITH_MYSQL_DATABASE:-app_db}
            MYSQL_USER: ${MONOLITH_MYSQL_USER:-app_user}
            MYSQL_PASSWORD: ${MONOLITH_MYSQL_PASSWORD:-helloworld}
        ports:
            - ${MONOLITH_MYSQL_PORT:-10002}:3306

    monolith.php:
        build:
            context: ./env/monolith/php
            dockerfile: Dockerfile
            args:
                TIMEZONE: ${TIMEZONE:-America/New_York}
        volumes:
            - ./services/monolith:/var/www/symfony/
            - monolith_composer_volume:/root/.composer

    webapp:
        build:
            context: ./env/webapp
            dockerfile: Dockerfile
        ports:
            - "${WEBAPP_VUE_CLI_UI_PORT:-11001}:8000"
            - "${WEBAPP_HTTP_PORT:-11002}:8080"
            - '3000:3000'
        volumes:
            - ./services/webapp:/var/webapp
        stdin_open: true
        tty: true
        environment:
            - CHOKIDAR_USEPOLLING=true
            - USE_VUE_UI=${WEBAPP_USE_VUE_UI:-0}
            - VUE_APP_MONOLITH_HTTP_PORT=${MONOLITH_HTTP_PORT:-10001}
        working_dir: /var/webapp

    accounts.nginx:
        build:
            context: ./env/accounts/nginx
            dockerfile: Dockerfile
        ports:
            - "${ACCOUNTS_HTTP_PORT:-12001}:80"
        volumes:
            - ./services/accounts:/var/www
        working_dir: /var/www
        depends_on:
            - accounts.php

    accounts.php:
        build:
            context: ./env/accounts/php
            dockerfile: Dockerfile
        environment:
            XDEBUG_PORT: ${ACCOUNTS_XDEBUG_PORT:-9001}
            COMPOSER_MEMORY_LIMIT: -1

        volumes:
            - ./services/accounts:/var/www
            - ./env/accounts/php/conf/docker-php-ext-xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini:cached
            - accounts_composer_volume:/root/.composer
        working_dir: /var/www
        depends_on:
            - accounts.db

    accounts.db:
        image: mysql:8.0.20
        command: --default-authentication-plugin=mysql_native_password
        volumes:
            - "accounts_db_volume:/var/lib/mysql"
        environment:
            MYSQL_ROOT_PASSWORD: ${ACCOUNTS_MYSQL_ROOT_PASSWORD:-root}
            MYSQL_DATABASE: ${ACCOUNTS_MYSQL_DATABASE:-accounts}
            MYSQL_USER: ${ACCOUNTS_MYSQL_USER:-accounts}
            MYSQL_PASSWORD: ${ACCOUNTS_MYSQL_PASSWORD:-accounts}
        ports:
            - ${ACCOUNTS_MYSQL_PORT:-12003}:3306

    accounts.redis:
        image: redis:5
        ports:
            - '${ACCOUNTS_REDIS_PORT:-12004}:6379'

    localstack:
        image: localstack/localstack:latest
        ports:
            - "4566:4566"
        environment:
            - SERVICES=sqs
            - DEBUG=1
            - PORT_WEB_UI=8080
            - DATA_DIR=/tmp/localstack/data
        volumes:
            - './env/localstack/data:/tmp/localstack'

volumes:
    monolith_db_volume:
    monolith_composer_volume:
    accounts_db_volume:
    accounts_composer_volume:

